---
title: "Figure"
output: html_document
date: '2022-07-21'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(multcomp)
library(ggplot2)
cbbpalette <- c( "#009E73", "#e79f00", "#9ad0f3", "#0072B2", "#D55E00", 
    "#CC79A7","#000000", "#F0E442") #colorblind and grayscale friendly.
```


Load the final model
```{r}
load("~/MAIHDA/eval_df.rda")
load("~/MAIHDA/SD_table.rda")
```

Difference from true score disaggregated
```{r}
ggplot(data=eval_df, aes(x=N_groups, y=dif, color=N_fac)) +

  geom_jitter(shape = 19,size=.05,  alpha=0.3, width=0.2) + 
 guides(colour = guide_legend(override.aes = list(size=5, alpha=1))) +

  theme(legend.position = "right",  axis.text.x=element_text(angle=0) , axis.ticks.x=element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"),text = element_text(size=16, color = "black")) +
  scale_color_manual(values=cbbpalette) +
  labs(color="Total sample \nsize", x="Group sample size") +

  ylab("True Error")  +
  scale_x_continuous(trans='log10') +
    geom_hline(yintercept=0, alpha = 0.3) +
    facet_grid(model ~ .) 

#Saves the image
ggsave("~/MAIHDA_SoEd/Score_disag.png", plot= last_plot(), dpi=300, width = 7.3, height = 3.25, units = "in", device = "png")
```

Difference from true score disaggregated (B&W)
```{r}
ggplot(data=eval_df, aes(x=N_groups, y=dif, color=N_fac)) +

  geom_jitter(shape = 19,size=.05,  alpha=0.3, width=0.2) + 
 guides(colour = guide_legend(override.aes = list(size=5, alpha=1))) +

  theme(legend.position = "right",  axis.text.x=element_text(angle=0) , axis.ticks.x=element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"),text = element_text(size=16, color = "black")) +
  scale_color_grey(start = 0,  end = 0.6,  na.value = "red",  aesthetics = "colour") +
  labs(color="Total sample \nsize", x="Group sample size") +

  ylab("True Error")  +
  scale_x_continuous(trans='log10') +
    geom_hline(yintercept=0, alpha = 0.3) +
    facet_grid(model ~ .) 

#Saves the image
ggsave("~/MAIHDA_SoEd/Score_disag_BW.png", plot= last_plot(), dpi=300, width = 7.3, height = 3.25, units = "in", device = "png")
```

Mean abs true error by Group sample size
```{r}

SD_table <- SD_table %>%
  mutate(N_fac = case_match(N_fac, "500" ~ "Total Sample = 500", "1000" ~ "Total Sample = 1000", "5000" ~ "Total Sample = 5000"),
         N_fac = factor(N_fac, levels=c("Total Sample = 500","Total Sample = 1000", "Total Sample = 5000")),
         model = factor(model, levels = c("Fixed Effect", "MAIHDA")))

ggplot(data=filter(SD_table), aes(x=as.factor(N_groups), y=mean)) +

  geom_point() +
  # geom_jitter(shape = 19,size=.05,  alpha=0.3, width=0.0) + 
 guides(colour = guide_legend(override.aes = list(size=1, alpha=1))) +

  theme(legend.position = "right",  axis.text.x=element_text(angle=0) , axis.ticks.x=element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"),text = element_text(size=16, color = "black")) +
  scale_color_manual(values=cbbpalette) +
  labs(color="Total sample \nsize", x="Group sample size") +

  ylab("Mean Absolute True Error")  +
  scale_y_continuous(limits = c(0,16)) +
  scale_x_discrete(breaks = c(0,5,10,15,20))+
        geom_hline(yintercept=4.4, alpha = 0.3, linetype = "dashed") +
      facet_grid(model ~ N_fac) 

#Saves the image
ggsave("~/MAIHDA_SoEd/True_error_20.png", plot= last_plot(), dpi=300, width = 7.3, height = 3.25, units = "in", device = "png")
```
